### PR TITLE
P1/feat/43 kanban card styling

### PR DESCRIPTION
**Pull request by netlightebba**

### CODE REVIEW

**Review by netlight-johannadagfalk — APPROVED** [review]
Looks good! :D 
I guess we wait with the checklist-item to have the same width as the carousel card ?

We should also add some margin/padding etc. but that is perhaps when the final design is up?

**Comment by netlightebba** [comment]
> Looks good! :D
> I guess we wait with the checklist-item to have the same width as the carousel card ?
> 
> We should also add some margin/padding etc. but that is perhaps when the final design is up?

Yes, this PR does not include styling of Achievements/badges (although they were affected), only the top column (accepted) cards  :D

**Comment by netlight-johannadagfalk** [comment]
That was not what I meant, I meant for the accepted cards :upside_down_face:

**Comment by netlightebba** [comment]
Now I understand Johanna hehe, but yes you are right. Although, we might have to discuss the width since the carousel cards don't have a fix width but adapts to the carousels size (but we can make it more similar ofc) 🤔

**Review by netlight-saraandersson — APPROVED** [review]
Awsome :D

**Pull request merged**
