### PR TITLE
Project 2 [feature]: Button answer component, saving answer to JSON object

### PR DESCRIPTION
**Pull request by e-ry**
Responsivity: Not worse than GoClimate webpage but text overflows for small screens, planned spike for solution

### CODE REVIEW

**Review by teolenn — CHANGES_REQUESTED** [review]
We need to add code comments. Especially the button answer selection logic.

**Comment by mabackstr** [comment]
Error handling moved to new task in backlog (due to block)

**Review by mabackstr — CHANGES_REQUESTED** [review]
Revert yarn.lock changes

**Review by mabackstr — APPROVED** [review]

**Comment by e-ry** [comment]
Stale branch, changes combined with numerical input

**Pull request closed without merging**
