### PR TITLE
P1/feat/63 expand items one at the time

### PR DESCRIPTION
**Pull request by netlight-johannadagfalk**

### CODE REVIEW

**Comment by elinaolsson** [comment]
Not sure I understand this PR. The check- and delete buttons work, but for me it still works to click anywhere on the card to expand/collapse it. And I can still open many cards at the same time. Am I doing something wrong or is there another problem?

**Review by elinaolsson — CHANGES_REQUESTED** [review]
Not sure I understand this PR. The check- and delete buttons work, but for me it still works to click anywhere on the card to expand/collapse it. And I can still open many cards at the same time. Am I doing something wrong or is there another problem?

**Comment by netlight-johannadagfalk** [comment]
There was code that disappeared in the rebase that I did not notice... try now !

**Review by elinaolsson — APPROVED** [review]
Much better 🤩

**Review by netlightebba — APPROVED** [review]
Nice 🙌

**Pull request merged**
